ALTER TABLE "Contact" DROP COLUMN IF EXISTS "addressLine1";
ALTER TABLE "Contact" DROP COLUMN IF EXISTS "city";
ALTER TABLE "Contact" DROP COLUMN IF EXISTS "state";
ALTER TABLE "Contact" DROP COLUMN IF EXISTS "postalCode";
ALTER TABLE "Contact" DROP COLUMN IF EXISTS "country";
