// Pre-built starter templates seeded for new users.
// Each template has all PdfTemplate fields except id, userId, businessId, createdAt, updatedAt.

const BASE = {
  paperSize: "A4",
  orientation: "portrait",
  marginTop: 0.4,
  marginBottom: 0.4,
  marginLeft: 0.4,
  marginRight: 0.4,
  fontSize: 10,
  showLogo: true,
  showWatermark: false,
  showPageNumbers: true,
  showItemNumbers: true,
  showTaxColumn: false,
  showTerms: false,
  termsText: null,
  showSignatureBlock: true,
  footerText: null,
  logoUrl: null,
  businessName: null,
  businessAddress: null,
  businessEmail: null,
  businessPhone: null,
};

// ─── Invoice Templates ──────────────────────────────────────────────────────

export const INVOICE_TEMPLATES = [
  {
    ...BASE,
    name: "Clean",
    type: "invoice",
    isDefault: true,
    headerStyle: "minimal",
    accentColor: "#18181b",
    fontFamily: "helvetica",
    tableHeaderBg: "#18181b",
    tableHeaderTextColor: "#ffffff",
  },
  {
    ...BASE,
    name: "Professional",
    type: "invoice",
    isDefault: false,
    headerStyle: "classic",
    accentColor: "#1e40af",
    fontFamily: "helvetica",
    tableHeaderBg: "#1e40af",
    tableHeaderTextColor: "#ffffff",
  },
  {
    ...BASE,
    name: "Creative",
    type: "invoice",
    isDefault: false,
    headerStyle: "bold",
    accentColor: "#dc2626",
    fontFamily: "helvetica",
    tableHeaderBg: "#dc2626",
    tableHeaderTextColor: "#ffffff",
  },
  {
    ...BASE,
    name: "Corporate",
    type: "invoice",
    isDefault: false,
    headerStyle: "classic",
    accentColor: "#0f766e",
    fontFamily: "times",
    tableHeaderBg: "#0f766e",
    tableHeaderTextColor: "#ffffff",
    fontSize: 11,
  },
];

// ─── Proposal Templates ─────────────────────────────────────────────────────

export const PROPOSAL_TEMPLATES = [
  {
    ...BASE,
    name: "Modern",
    type: "proposal",
    isDefault: true,
    headerStyle: "minimal",
    accentColor: "#18181b",
    fontFamily: "helvetica",
    tableHeaderBg: "#18181b",
    tableHeaderTextColor: "#ffffff",
    showSignatureBlock: true,
  },
  {
    ...BASE,
    name: "Executive",
    type: "proposal",
    isDefault: false,
    headerStyle: "bold",
    accentColor: "#1e3a5f",
    fontFamily: "times",
    tableHeaderBg: "#1e3a5f",
    tableHeaderTextColor: "#ffffff",
    showSignatureBlock: true,
    fontSize: 11,
  },
  {
    ...BASE,
    name: "Studio",
    type: "proposal",
    isDefault: false,
    headerStyle: "classic",
    accentColor: "#7c3aed",
    fontFamily: "helvetica",
    tableHeaderBg: "#7c3aed",
    tableHeaderTextColor: "#ffffff",
    showSignatureBlock: true,
  },
];

// ─── Contract Templates ─────────────────────────────────────────────────────

export const CONTRACT_TEMPLATES = [
  {
    ...BASE,
    name: "Standard",
    type: "contract",
    isDefault: true,
    headerStyle: "classic",
    accentColor: "#18181b",
    fontFamily: "helvetica",
    tableHeaderBg: "#18181b",
    tableHeaderTextColor: "#ffffff",
    showSignatureBlock: true,
    showTerms: true,
    termsText: "This contract is binding upon signature by both parties.",
  },
  {
    ...BASE,
    name: "Formal",
    type: "contract",
    isDefault: false,
    headerStyle: "classic",
    accentColor: "#1e3a5f",
    fontFamily: "times",
    tableHeaderBg: "#1e3a5f",
    tableHeaderTextColor: "#ffffff",
    showSignatureBlock: true,
    showTerms: true,
    termsText: "This contract is binding upon signature by both parties.",
    fontSize: 11,
  },
  {
    ...BASE,
    name: "Minimal",
    type: "contract",
    isDefault: false,
    headerStyle: "minimal",
    accentColor: "#374151",
    fontFamily: "helvetica",
    tableHeaderBg: "#374151",
    tableHeaderTextColor: "#ffffff",
    showSignatureBlock: true,
  },
];

export const ALL_STARTER_TEMPLATES = [
  ...INVOICE_TEMPLATES,
  ...PROPOSAL_TEMPLATES,
  ...CONTRACT_TEMPLATES,
];
